### ISSUE TITLE
Feedback on week 13 project progress for CS2113T-F11-4

### ISSUE THREAD

**Issue by nus-pe-script** [AY1920S1-CS2113T-F11-4/main#303]
## Team progress for `v1.4`
* Milestone `v1.4` properly managed:
   * [x] A suitable deadline set [your deadline: 2019-11-11] (:heavy_check_mark: well done!)
   * [x] All issues in this milestone are closed(:heavy_check_mark: well done!)
   * [x] Milestone explicitly closed(:heavy_check_mark: well done!)
* [x] New JAR released on GitHub in the past 2 weeks (:heavy_check_mark: well done!)
## Individual progress of @dng132fei for `v1.4`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks (:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.4` milestone https://github.com/AY1920S1-CS2113T-F11-4/main/issues/215 https://github.com/AY1920S1-CS2113T-F11-4/main/issues/207 https://github.com/AY1920S1-CS2113T-F11-4/main/issues/171 https://github.com/AY1920S1-CS2113T-F11-4/main/issues/161 (:heavy_check_mark: well done!)
* [ ] (not graded) Ensured the PPP file has links to your reposense report (:question: tick this yourself after completing the item)
## Individual progress of @ryan-wong-ren-wei for `v1.4`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks (:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.4` milestone https://github.com/AY1920S1-CS2113T-F11-4/main/issues/205 https://github.com/AY1920S1-CS2113T-F11-4/main/issues/194 https://github.com/AY1920S1-CS2113T-F11-4/main/issues/183 https://github.com/AY1920S1-CS2113T-F11-4/main/issues/175 https://github.com/AY1920S1-CS2113T-F11-4/main/issues/173 https://github.com/AY1920S1-CS2113T-F11-4/main/issues/167 https://github.com/AY1920S1-CS2113T-F11-4/main/issues/160 (:heavy_check_mark: well done!)
* [ ] (not graded) Ensured the PPP file has links to your reposense report (:question: tick this yourself after completing the item)
## Individual progress of @yenpeichih for `v1.4`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks (:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.4` milestone https://github.com/AY1920S1-CS2113T-F11-4/main/issues/209 https://github.com/AY1920S1-CS2113T-F11-4/main/issues/197 https://github.com/AY1920S1-CS2113T-F11-4/main/issues/190 (:heavy_check_mark: well done!)
* [ ] (not graded) Ensured the PPP file has links to your reposense report (:question: tick this yourself after completing the item)
## Individual progress of @yuanjiayi for `v1.4`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks (:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.4` milestone https://github.com/AY1920S1-CS2113T-F11-4/main/issues/213 https://github.com/AY1920S1-CS2113T-F11-4/main/issues/212 https://github.com/AY1920S1-CS2113T-F11-4/main/issues/203 https://github.com/AY1920S1-CS2113T-F11-4/main/issues/199 https://github.com/AY1920S1-CS2113T-F11-4/main/issues/170 (:heavy_check_mark: well done!)
* [ ] (not graded) Ensured the PPP file has links to your reposense report (:question: tick this yourself after completing the item)
## Individual progress of @zhangyihannus for `v1.4`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks (:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.4` milestone https://github.com/AY1920S1-CS2113T-F11-4/main/issues/226 https://github.com/AY1920S1-CS2113T-F11-4/main/issues/222 https://github.com/AY1920S1-CS2113T-F11-4/main/issues/210 https://github.com/AY1920S1-CS2113T-F11-4/main/issues/198 https://github.com/AY1920S1-CS2113T-F11-4/main/issues/195 https://github.com/AY1920S1-CS2113T-F11-4/main/issues/164 (:heavy_check_mark: well done!)
* [ ] (not graded) Ensured the PPP file has links to your reposense report (:question: tick this yourself after completing the item)

Tutor: @leowweixiang

Please reply in this thread if there are any inaccuracies in the above observations.

 <sub> Note: the above observation was done by the CS2113-feedback-bot and covers changes up to 2019-11-15 00:00:00 only. If you think the above observation is incorrect, please let us know by replying in this thread. Please include links to relevant PRs/comments in your response.</sub>
